[[section-system-scope-and-context]]  

== System Scope and Context    

=== Business Context

[plantuml, "businesscontext", png]
----
database "User's POD" as Pod
component "WebApp" as WApp
component "OpenStreetMaps" as Map
:User: --> [Pod]: Creates
:User: --> [WApp]: Interacts
[WApp] --> [Pod]: Request permissions
[Pod] --> [WApp]: User's information
[WApp] --> [Map]: Show markers
----

[options="header",cols="1,4,4"] 
|===  
|Entity |Inputs | Outputs  

| *_User_*
| The user's input will be the interface provided by the webapp.
| The user will create the pod and store there their information and also, he can customize the map by adding places.

| *_POD_*
| The POD will receive petitions from WebApp to get information about the users of the app.  
| It will provide users' information (places registered by users) needed by the webapp. 

| *_WebApp_*
| The user will be able to add markers and to access the information about their markers.
| The information that provides to the user logged like the added markers and their details.

| *_OpenStreetMaps_*
| It allows us to create markers with different information about places.
| It allows us to view in the map the different markers created by users

|===    

=== Technical Context  

[plantuml, "technicalcontext", png]
----
Actor User as user

node device as "Device" {
    component pc as "PC"
    component mobile as "Mobile"
    component tablet as "Tablet"
    component more as "More..."
}

component browser as "Web Browser"

node cloud as "AzureCloud"{    
    node webapp as "WebApp" {
        component views as "Views"
        component api as "OpenStreetMap"
    }
}

database POD

user -down..> webapp: interacts
user -right-> device: uses
device -down-> browser: connects to
browser -left-> cloud: requests (HTTPS)
webapp <-down-> POD: accesses
views -right-> api: gets services from
----

The main objective of the application is the private treatment of user data. We will achieve this objective by using PODs to keep user data private and decentralized. 

In SOLID architecture we can define a POD as a Personal Online Data Store. The user can have there any information he/she wants and can be hosted anywhere.  

The application will be written in Typescript with React, Typescript being a language like JavaScript but with types and React a library to facilitate the creation of user interfaces.  

[options="header",cols="2,7"] 
|===    
|Technical Interface| Description  

| *_SOLID_*  
| Architecture followed in the project that determines the structure of the data management. Most of the data is decentralized and stored in a secure way on PODs.

| *_TypeScript_*
| Language used to build the application.

| *_React_*
| Library to help the building of the user interfaces and to make frontend development easier.

| *_PODs_*
| Management of user data in a private and decentralized way according to the SOLID architecture.
|=== 