[[section-system-scope-and-context]]  

== System Scope and Context    

=== Business Context

[plantuml, "businesscontext", png]
----
component "GOMap!" as go
:User: --> [go]: Add marker
:Hall: --> [go]: Add review
:Bussiness: --> [go]: Create map
[go] .-> User: Load markers
[go] .-> Bussiness: Load maps
[go] .-> Hall: Load reviews
----

[options="header",cols="1,4,4"] 
|===  
|Entity |Inputs | Outputs


| *_GOMap!_*
| Users interaction with the graphic interface.
| Response to the users' inputs obtained from the PODs (place to store information)

| *_User, Hall & Bussiness_*
| All users' input will be the interface provided by the webapp.
| Users will create the POD, store there their information and also, he can customize the map by adding places, changing between different maps, or even add reviews or info to other users markers.


|===    

=== Technical Context  

[plantuml, "technicalcontext", png]
----
Actor User as user

node device as "Device" {
    component browser as "Web Browser"
}
note left of device: compatible with multiple devices


node cloud as "AzureCloud"{    
    node webapp as "WebApp" {
        component views as "Views"
    }
}

component api as "OpenStreetMap"

database POD

user -down..> webapp: interacts
user -right-> device: uses
device -down-> browser: has
browser -left-> cloud: requests (HTTPS)
webapp <-down-> POD: accesses
views -right-> api: gets services from
----

The main objective of the application is the private treatment of user data. We will achieve this objective by using PODs to keep user data private and decentralized. 

In SOLID architecture we can define a POD as a Personal Online Data Store. The user can have there any information he/she wants and can be hosted anywhere.  

The application will be written in Typescript with React, Typescript being a language like JavaScript but with types and React a library to facilitate the creation of user interfaces.  

[options="header",cols="2,7"] 
|===    
|Technical Interface| Description  

| *_SOLID_*  
| Architecture followed in the project that determines the structure of the data management. Most of the data is decentralized and stored in a secure way on PODs.

| *_TypeScript_*
| Language used to build the application.

| *_React_*
| Library to help the building of the user interfaces and to make frontend development easier.

| *_PODs_*
| Management of user data in a private and decentralized way according to the SOLID architecture.
|=== 