[[section-building-block-view]] 

== Building block view 

=== Level 1: Whitebox of the Overall System 

[plantuml, "level1", png] 

---- 

Actor Israel 

Component GoMap 

Component pod as "Pod's service" 

Israel -right-> GoMap: interacts with 

GoMap <-right-> Pod: gets data 

----   

Motivation::

_GOMap!®_ application is the general structure of a system in which users will have the possibility to add markers to their favorite places and share them with their friends.  All the data that belongs to the user is stored safely in their _PODs_. 

Contained Building Blocks:: 

[options="header",cols="1,3"] 

|=== 

|Name| Description  

|*User*  
|Client of the application which will interact with it. 

|*GOMap!® application*  
|System developed to be used by the users. Through its information in the PODs will be taken.   

|*PODs service* 
|Has the aim to access each user's personal POD. 

|=== 

=== Level 2 

[plantuml, "level2", png] 

---- 

Actor Israel 

Component GoMap { 

    Component ui as "User Interface" 

    Component da as "Data Access" 

    Database db as "MongoDB" 

} 

Component pod as "Pod's service" 

  

Israel-right-> ui 

ui <-right-> da: data 

da <--> db: data flow 

da <--> pod: get address 

---- 

Motivation:: 

Shows how the application will work internally in general terms. The client, through the user interface, will get the data requested by using the _DAL_ (_Data Access Layer_). 

Contained Building Blocks:: 

[options="header",cols="1,3"] 

|=== 

|Name| Description 

|*User Interface*  
|The user will interact with this UI to request any information about the map. This means the user will be able to perform any task in our system through this. 

|*Data Access* 
|The layer that will provide and request information from and to the _PODs_ and the _Database_. 

|*MongoDB*  
|_Database_ used to store the minimum data as possible from the users. We especially use this database to store the id of the users in order to link their profile with the personal POD. 

|=== 

=== Level 3 

[plantuml, "level3", png] 

---- 

Actor Israel   

Component Interface{ 

    Component vi as "Views"{ 

       Component ho as "Home" 

       Component marker as "Marker" 

       Component mm as "Markers" 

       Component map as "Map" 

       Component lo as "Sign in" 

       Component re as "Sign up" 

       Component out as "Log out"        

       Component rw as "Review" 

    }     

}   

Component DataAccess{ 

       Component sol as "Solid" 

       Component res as "RestApi" 

       Component le as "Locations Api" 

}   

Component pod as "Pod's service" 

Database db as "MongoDB" 

Israel -right->Interface: interacts 


re -right-> sol 

rw -down-> sol 
  

re-right->res 

map-right->res 

lo-right->res 

marker-right->res 

my-right->res 
   

rw -down->le 
  

sol <-down-> pod:acceses 

res <-down-> db:data 

---- 
  

Motivation:: 

Detailed structure of the system. Focused on the components of the _User Interface_ and _Data Access_. 


Contained Building Blocks:: 

[options="header",cols="1,3"] 

|=== 

|Name| Description   

|*Views*  
|Sections of the application where the user is going to interact with the system. 

|*Home* 
|Initial screen of the application. A welcome message is going to be displayed as well as the featured products. 

|*Marker* 
|View information about a certain location in the map. Here the user will be able to add reviews and photos about that place. 

|*Markers* 
|The user has a markers view, where he will see the markers that the user and his friends have previously created. 

|*Sign-in* 
|Here the user will log-in into their personal account. In case they have created one previously. 

|*Sign-up* 
|Allows the client to create a new account for the application. This process will take place only once for each user. 

|*Map* 
|Here the user can find everything the app is designed to, from markers created by user to certain locations. 

|*Log-out* 
|It logs the user out from the application. 

|*Review* 
|At this point, the user will add a review about the restaurant, bar, shop, etc associated to the marker. 

|*RestAPI* 
|The application resquest the _RestAPI_ for the information needed. Receiving a response from _MongoDB_. 

|=== 
