[[section-runtime-view]] 

== Runtime View 

=== Login 

For the login, the app shows the login view which asks the user for their Solid Identity Provider of choice. 

Then the app does a login request to the REST API server, which redirects the user to the identity provider which handles the authentication. 

Once the user successfully logs in, the identity provider gives the server the session information needed to interact with the user Pod, and the server sends the session ID to the web app, which can be used to identify the session in later REST API requests. Lastly, the web app shows the main view. 

[plantuml,"Sequence diagram - Login",png] 

---- 

actor User as User 

participant "Web App" as W 

participant "REST API Server" as R 

participant "Solid Identity Provider" as P 
  

activate W 

W -> W: Show Login View 

U -> W: Chooses Solid Identity Provider 

W -> R: Requests login 

deactivate W 

activate R 

R -> P: Redirects to the provider login form 

deactivate R 

activate P 

P --> U: Asks for credentials 

activate U 

U -> P: Logs in 

deactivate U 

P --> R: Provides session information 

deactivate P 

activate R 

R --> W: Provides session ID 

activate W 

W -> W: Show Main View 

----  

=== List friends 

 In this view he can do the CRUD operations: 

The users enter the app and go to the friend's view. 

The client receives the request and sends the server for the friends list. 

The server asks the POD for the friends. 

The POD return the list to the client 

The client receives the list and shows it to the user. 

 
[plantuml,"Sequence diagram - Nearby friends",png] 

---- 

actor User 
participant Client 
participant "Web App" as W  
database Pod as "Pod" 
User -> Client: Request friend’s view 
Client --> W: Request friend’s list 
W --> Pod: Search for the list 
W <-- Pod: Return the list 
Client <-- W: Return the list of friends 
User <- Client: Return the list view 

----   

=== Add Location   

Saved locations can later be viewed by the user and his friends through the web application. 

The user can add a location to their map.   

[plantuml,"Sequence diagram - Saving Locations - mobileapp",png] 

---- 

actor User 
participant "Web App" as W  
database Pod as "Pod" 
 
User-> W: User click the map to add a new marker 
W ->Pod: Ask locations JSON 
Pod-> W: Return locations JSON 
W -> W: Add the new location 
W ->Pod: Sends the new JSON 
W ->User: Show the map with the new location. 

----  

=== Remove Location 

Locations added to the map later be removed by the user through the application.  

[plantuml,"Sequence diagram - Editing Saved Locations",png] 

---- 

actor User 
participant "Web App" as W   
database Pod as "Pod" 
 
User-> W: User click the map in one mark location 

W -> W: Using the location ID the app knows the JSON file 
W ->Pod: Ask locations JSON 
Pod-> W: Return locations JSON 
W -> W: Remove certain location 
W ->Pod: Sends the new JSON 
W ->User: Show the map with the new location. 

---- 
