[[section-runtime-view]] 

== Runtime View 

=== Login 

For the login, the app shows the login view which asks the user for their Solid Identity Provider of choice. 

Then the app does a login request to the REST API server, which redirects the user to the identity provider which handles the authentication. 

Once the user successfully logs in, the identity provider gives the server the session information needed to interact with the user Pod, and the server sends the session ID to the web app, which can be used to identify the session in later REST API requests. Lastly, the web app shows the main view. 

[plantuml,"sequencediagram-login",png] 

---- 
actor User as U
participant "Web App" as W 
participant "SOLID Identity Provider" as P 
activate W 
W -> W: Show Login View 
U -> W: Chooses Solid Identity Provider 
W -> P: Requests login 
deactivate W 
activate P 
P -> P: Redirects to the provider login form 
P --> U: Asks for credentials 
deactivate P
activate U 
U -> P: Logs in 
deactivate U 
activate P
P --> P: Provides session information 
P --> W: Provides session ID 
deactivate P
activate W 
W -> W: Show Main View
deactivate P
----  

=== List friends 

In this view he can do the CRUD operations: 

* The users enter the app and go to the friend's view. 
* The client receives the request and sends the server for the friends list. 
* The server asks the POD for the friends. 
* The POD return the list to the client.
* The client receives the list and shows it to the user. 

 
[plantuml,"sequencediagram-nearbyfriends",png] 

---- 
actor User 
participant Client 
participant "Web App" as W  
database Pod as "Pod" 
User -> Client: Request friend’s view 
Client --> W: Request friend’s list 
W --> Pod: Search for the list 
W <-- Pod: Return the list 
Client <-- W: Return the list of friends 
User <- Client: Return the list view 
----   

=== Add Location   

Saved locations can later be viewed by the user and his friends through the web application. 

The user can add a location to their map.   

[plantuml,"sequencediagram-savinglocations",png] 

---- 
actor User 
participant "Web App" as W  
database Pod as "Pod"  
User-> W: User click the map to add a new marker 
W ->Pod: Ask locations JSON 
Pod-> W: Return locations JSON 
W -> W: Add the new location 
W ->Pod: Sends the new JSON 
W ->User: Show the map with the new location. 
----  

=== Remove Location 

Locations added to the map later be removed by the user through the application.  

[plantuml,"sequencediagram-editingsavedlocations",png] 

---- 
actor User 
participant "Web App" as W   
database Pod as "Pod"  
User-> W: User click the map in one mark location 
W -> W: Using the location ID the app knows the JSON file 
W ->Pod: Ask locations JSON 
Pod-> W: Return locations JSON 
W -> W: Remove certain location 
W ->Pod: Sends the new JSON 
W ->User: Show the map with the new location. 
---- 
