[[section-deployment-view]]
== Deployment View
 
=== Infrastructure Level 1
 
[plantuml, "infrastructure-level1", png]
----
node AzureServer{    
    node DockerContainer2 {
        component WebApp
    }    
}
 
node UserDevice {
    node WebBrowser {
        component WebAppImage
    }
}
 
Actor User
 
node SOLID_POD
node OpenStreetMap
 
WebAppImage -d-> SOLID_POD : "access user data"
WebAppImage -d-> OpenStreetMap : "provides maps and route image"
WebApp -d-> WebAppImage : 'shows on user device'
WebAppImage <-l- User
----
 
==== Motivation
In the development stage the application will be running on each student's machine. However, in the production stage the application will be running on a Docker environment hosted on _Azure_. Our objective is to know how to use docker correctly, which is the infrastructure on which our application will be running.
 
==== Quality and/or performance features
The performance of the application depends on different user resources (internet connection, hardware, etc) as well as on the _Azure_ servers device. For that reason, it is not in our hand to ensure these resources. Anyway we will make the required optimizations in order to maximize the performance and quality and we have used the best technologies at our disposal, trying to minimise waiting times for user requests. It should be noted that our main quality goals are privacy, usability and maintainability.
 
==== Mapping of building blocks to infrastructure

[options="header",cols="1,4"]
|===
| Element | Description
 
| *_WebApp_*
| The frontend of our application. It will be rendered by a web browser which will be executed ont the user's device.

| *_POD Provider_*
| _SOLID PODs_ will be provided by _Solid Community_. Will be in charge of providing the pods for the users
 
| *_Client Device_*
| Device of the user (desktop, mobile). Must have internet connection.
|===
